spring.application.name=The-Journey-Book-Backend

# MongoDB Atlas Connection
spring.data.mongodb.uri=${MONGODB_ATLAS_URI}

# Server Port
server.port=8080

# Google OAuth2 Configuration
#spring.security.oauth2.client.registration.google.client-id=${GOOGLE_OAUTH_CLIENT_ID}
#spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_OAUTH_CLIENT_SECRET}
#spring.security.oauth2.client.registration.google.scope=profile,email

# REMOVE THESE LINES - Spring Security handles redirect URI automatically
# spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google
# spring.security.oauth2.client.registration.google.redirect-uri=https://the-journey-book-backend.onrender.com/login/oauth2/code/google

# Google Places
google.api.key=${GOOGLE_PLACES_API_KEY}

# Razorpay Configuration
razorpay.key.id=${RAZORPAY_ID}
razorpay.key.secret=${RAZORPAY_SECRET}

# Frontend URL for OAuth2 success redirect
#frontend.oauth2.success-url=https://the-journey-book.netlify.app/oauth2-success

# Update these Auth0 values with your actual application credentials:
auth0.domain=dev-4x4wk6evx87nelgb.us.auth0.com
auth0.clientId=SRcSMKIusbAcVufJVUV0ki6KpQdf95xP
auth0.clientSecret=CWHzkOiv9HGhuQ4FXsz-Xfhwgvv0R19o88yADNsGzSvUENVAwGdUn-0b0fQXYl9W
auth0.audience=https://dev-4x4wk6evx87nelgb.us.auth0.com/api/v2/


spring.data.redis.url=${UPSTASH_REDIS_URL}
logging.level.io.lettuce.core=DEBUG
logging.level.org.springframework.data.redis=DEBUG