spring.application.name=The-Journey-Book-Backend

# MongoDB Atlas Connection
spring.data.mongodb.uri=mongodb+srv://janisar3922:Akhtar423@cluster0.ba5eh7s.mongodb.net/journey_book_db?retryWrites=true&w=majority&appName=Cluster0

# Server Port
server.port=8080

# Enable logging to debug
logging.level.org.springframework.data.mongodb=DEBUG

# Google OAuth2 Configuration
spring.security.oauth2.client.registration.google.client-id=YOUR_GOOGLE_CLIENT_ID
spring.security.oauth2.client.registration.google.client-secret=YOUR_GOOGLE_CLIENT_SECRET
spring.security.oauth2.client.registration.google.scope=profile,email

# Redirect URL after successful login
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google